# Generated by Django 5.2.7 on 2025-11-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_member_alter_book_authors_alter_book_isbn_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',)},
        ),
    ]
